In [252]:
import os
import sys
import pandas as pd
import json
import re

In [436]:
results_file = 'results.json'

In [503]:
sram_dp = pd.DataFrame()
tcam_dp = pd.DataFrame()
for root, subdirs, files in os.walk('.'):
    if results_file in files:
        js = pd.read_json(root +'/' + results_file)
        number = re.search(r"./(.*)-results-\d*-(\d*).*", root)
        #print(number.groups())
        t = js['latency'].dropna()[1]['7']['latency'] | {'n_clients': number.groups()[1]} | {'type':  number.groups()[0]}
        tcam_dp = tcam_dp.append(t, ignore_index=True)

In [507]:
q_low = tcam_dp["total_max"].quantile(0.01)
q_hi  = tcam_dp["total_max"].quantile(0.99)

dp_filtered = tcam_dp[( tcam_dp["total_max"] < q_hi) & ( tcam_dp["total_max"] > q_low)]

In [508]:
tcam_dp

,jitter,average,total_max,total_min,last_max,histogram,n_clients,type
0,0.0,4.0,17.0,4.0,5.0,"{'0': 5990, '10': 9, '10000': 1}",1,sram
1,0.0,4.0,15.0,4.0,6.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
2,0.0,5.0,531.0,4.0,5.0,"{'0': 5986, '10': 12, '10000': 1, '500': 1}",1,sram
3,0.0,5.0,17.0,4.0,6.0,"{'0': 5990, '10': 9, '10000': 1}",1,sram
4,0.0,5.0,14.0,4.0,5.0,"{'0': 5988, '10': 11, '10000': 1}",1,sram
5,0.0,4.0,17.0,4.0,5.0,"{'0': 5987, '10': 12, '10000': 1}",1,sram
6,0.0,5.0,14.0,4.0,6.0,"{'0': 5984, '10': 15, '10000': 1}",1,sram
7,0.0,5.0,14.0,4.0,5.0,"{'0': 5989, '10': 10, '10000': 1}",1,sram
8,0.0,5.0,16.0,4.0,6.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
9,0.0,5.0,15.0,4.0,6.0,"{'0': 5990, '10': 9, '10000': 1}",1,sram
10,0.0,5.0,18.0,4.0,5.0,"{'0': 5989, '10': 10, '10000': 1}",1,sram
11,0.0,5.0,15.0,4.0,6.0,"{'0': 5985, '10': 14, '10000': 1}",1,sram
12,0.0,5.0,17.0,4.0,5.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
13,0.0,5.0,16.0,4.0,5.0,"{'0': 5984, '10': 15, '10000': 1}",1,sram
14,0.0,5.0,21.0,4.0,5.0,"{'0': 5987, '10': 11, '10000': 1, '20': 1}",1,sram
15,0.0,4.0,15.0,4.0,5.0,"{'0': 5984, '10': 15, '10000': 1}",1,sram
16,0.0,4.0,21.0,4.0,5.0,"{'0': 5986, '10': 12, '10000': 1, '20': 1}",1,sram
17,0.0,5.0,6573.0,4.0,5.0,"{'0': 5988, '10': 10, '10000': 1, '6000': 1}",1,sram
18,0.0,4.0,14.0,4.0,6.0,"{'0': 5994, '10': 5, '10000': 1}",1,sram
19,0.0,7.0,582.0,4.0,6.0,"{'0': 5986, '10': 12, '10000': 1, '500': 1}",1,sram
20,0.0,4.0,17.0,4.0,5.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
21,0.0,5.0,16.0,4.0,6.0,"{'0': 5992, '10': 7, '10000': 1}",1,sram
22,0.0,5.0,16.0,4.0,5.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
23,0.0,5.0,15.0,4.0,5.0,"{'0': 5993, '10': 6, '10000': 1}",1,sram
24,0.0,5.0,15.0,4.0,5.0,"{'0': 5988, '10': 11, '10000': 1}",1,sram
25,0.0,4.0,15.0,4.0,5.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
26,0.0,5.0,21.0,4.0,6.0,"{'0': 5987, '10': 11, '10000': 1, '20': 1}",1,sram
27,0.0,5.0,18.0,4.0,5.0,"{'0': 5985, '10': 14, '10000': 1}",1,sram
28,0.0,5.0,15.0,4.0,5.0,"{'0': 5990, '10': 9, '10000': 1}",1,sram
29,0.0,5.0,14.0,4.0,5.0,"{'0': 5984, '10': 15, '10000': 1}",1,sram
30,0.0,5.0,14.0,4.0,5.0,"{'0': 5985, '10': 14, '10000': 1}",1,sram
31,0.0,5.0,5113.0,4.0,5.0,"{'0': 5985, '10': 13, '10000': 1, '5000': 1}",1,tcam
32,0.0,5.0,15.0,4.0,5.0,"{'0': 5985, '10': 14, '10000': 1}",1,tcam
33,0.0,5.0,14.0,4.0,6.0,"{'0': 5988, '10': 11, '10000': 1}",1,tcam
34,0.0,4.0,16.0,4.0,5.0,"{'0': 5991, '10': 8, '10000': 1}",1,tcam
35,0.0,4.0,15.0,4.0,5.0,"{'0': 5989, '10': 10, '10000': 1}",1,tcam
36,0.0,5.0,859.0,4.0,7.0,"{'0': 5985, '10': 12, '100': 1, '10000': 1, '8...",1,tcam
37,0.0,5.0,15.0,4.0,5.0,"{'0': 5987, '10': 12, '10000': 1}",1,tcam
38,0.0,5.0,5972.0,4.0,5.0,"{'0': 5990, '10': 8, '10000': 1, '5000': 1}",1,tcam
39,0.0,5.0,14.0,4.0,6.0,"{'0': 5990, '10': 9, '10000': 1}",1,tcam
40,0.0,4.0,15.0,4.0,5.0,"{'0': 5990, '10': 9, '10000': 1}",1,tcam
41,0.0,4.0,16.0,3.0,5.0,"{'0': 5989, '10': 10, '10000': 1}",1,tcam
42,0.0,5.0,17.0,4.0,5.0,"{'0': 5992, '10': 7, '10000': 1}",1,tcam
43,0.0,5.0,17.0,4.0,5.0,"{'0': 5978, '10': 21, '7000': 1}",1000,tcam
44,0.0,5.0,18.0,4.0,6.0,"{'0': 5986, '10': 12, '10000': 1, '20': 1}",1000,tcam
45,0.0,5.0,18.0,4.0,5.0,"{'0': 5982, '10': 16, '20': 1, '4000': 1}",1000,tcam
46,0.0,5.0,18.0,4.0,5.0,"{'0': 5983, '10': 16, '8000': 1}",1000,tcam
47,0.0,5.0,25.0,4.0,6.0,"{'0': 5983, '10': 15, '10000': 1, '20': 1}",1000,tcam
48,0.0,5.0,5061.0,4.0,6.0,"{'0': 5984, '10': 13, '20': 1, '4000': 1, '500...",1000,tcam
49,0.0,5.0,17.0,4.0,7.0,"{'0': 5986, '10': 13, '4000': 1}",1000,tcam
50,0.0,5.0,25.0,4.0,5.0,"{'0': 5985, '10': 13, '20': 1, '4000': 1}",1000,tcam
51,0.0,5.0,17.0,4.0,5.0,"{'0': 5980, '10': 19, '4000': 1}",1000,tcam
52,0.0,5.0,18.0,4.0,5.0,"{'0': 5984, '10': 15, '4000': 1}",1000,tcam

In [513]:
dp_filtered

,jitter,average,total_max,total_min,last_max,histogram,n_clients,type
0,0.0,4.0,17.0,4.0,5.0,"{'0': 5990, '10': 9, '10000': 1}",1,sram
1,0.0,4.0,15.0,4.0,6.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
2,0.0,5.0,531.0,4.0,5.0,"{'0': 5986, '10': 12, '10000': 1, '500': 1}",1,sram
3,0.0,5.0,17.0,4.0,6.0,"{'0': 5990, '10': 9, '10000': 1}",1,sram
5,0.0,4.0,17.0,4.0,5.0,"{'0': 5987, '10': 12, '10000': 1}",1,sram
8,0.0,5.0,16.0,4.0,6.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
9,0.0,5.0,15.0,4.0,6.0,"{'0': 5990, '10': 9, '10000': 1}",1,sram
10,0.0,5.0,18.0,4.0,5.0,"{'0': 5989, '10': 10, '10000': 1}",1,sram
11,0.0,5.0,15.0,4.0,6.0,"{'0': 5985, '10': 14, '10000': 1}",1,sram
12,0.0,5.0,17.0,4.0,5.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
13,0.0,5.0,16.0,4.0,5.0,"{'0': 5984, '10': 15, '10000': 1}",1,sram
14,0.0,5.0,21.0,4.0,5.0,"{'0': 5987, '10': 11, '10000': 1, '20': 1}",1,sram
15,0.0,4.0,15.0,4.0,5.0,"{'0': 5984, '10': 15, '10000': 1}",1,sram
16,0.0,4.0,21.0,4.0,5.0,"{'0': 5986, '10': 12, '10000': 1, '20': 1}",1,sram
19,0.0,7.0,582.0,4.0,6.0,"{'0': 5986, '10': 12, '10000': 1, '500': 1}",1,sram
20,0.0,4.0,17.0,4.0,5.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
21,0.0,5.0,16.0,4.0,6.0,"{'0': 5992, '10': 7, '10000': 1}",1,sram
22,0.0,5.0,16.0,4.0,5.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
23,0.0,5.0,15.0,4.0,5.0,"{'0': 5993, '10': 6, '10000': 1}",1,sram
24,0.0,5.0,15.0,4.0,5.0,"{'0': 5988, '10': 11, '10000': 1}",1,sram
25,0.0,4.0,15.0,4.0,5.0,"{'0': 5991, '10': 8, '10000': 1}",1,sram
26,0.0,5.0,21.0,4.0,6.0,"{'0': 5987, '10': 11, '10000': 1, '20': 1}",1,sram
27,0.0,5.0,18.0,4.0,5.0,"{'0': 5985, '10': 14, '10000': 1}",1,sram
28,0.0,5.0,15.0,4.0,5.0,"{'0': 5990, '10': 9, '10000': 1}",1,sram
31,0.0,5.0,5113.0,4.0,5.0,"{'0': 5985, '10': 13, '10000': 1, '5000': 1}",1,tcam
32,0.0,5.0,15.0,4.0,5.0,"{'0': 5985, '10': 14, '10000': 1}",1,tcam
34,0.0,4.0,16.0,4.0,5.0,"{'0': 5991, '10': 8, '10000': 1}",1,tcam
35,0.0,4.0,15.0,4.0,5.0,"{'0': 5989, '10': 10, '10000': 1}",1,tcam
36,0.0,5.0,859.0,4.0,7.0,"{'0': 5985, '10': 12, '100': 1, '10000': 1, '8...",1,tcam
37,0.0,5.0,15.0,4.0,5.0,"{'0': 5987, '10': 12, '10000': 1}",1,tcam
38,0.0,5.0,5972.0,4.0,5.0,"{'0': 5990, '10': 8, '10000': 1, '5000': 1}",1,tcam
40,0.0,4.0,15.0,4.0,5.0,"{'0': 5990, '10': 9, '10000': 1}",1,tcam
41,0.0,4.0,16.0,3.0,5.0,"{'0': 5989, '10': 10, '10000': 1}",1,tcam
42,0.0,5.0,17.0,4.0,5.0,"{'0': 5992, '10': 7, '10000': 1}",1,tcam
43,0.0,5.0,17.0,4.0,5.0,"{'0': 5978, '10': 21, '7000': 1}",1000,tcam
44,0.0,5.0,18.0,4.0,6.0,"{'0': 5986, '10': 12, '10000': 1, '20': 1}",1000,tcam
45,0.0,5.0,18.0,4.0,5.0,"{'0': 5982, '10': 16, '20': 1, '4000': 1}",1000,tcam
46,0.0,5.0,18.0,4.0,5.0,"{'0': 5983, '10': 16, '8000': 1}",1000,tcam
47,0.0,5.0,25.0,4.0,6.0,"{'0': 5983, '10': 15, '10000': 1, '20': 1}",1000,tcam
48,0.0,5.0,5061.0,4.0,6.0,"{'0': 5984, '10': 13, '20': 1, '4000': 1, '500...",1000,tcam
49,0.0,5.0,17.0,4.0,7.0,"{'0': 5986, '10': 13, '4000': 1}",1000,tcam
50,0.0,5.0,25.0,4.0,5.0,"{'0': 5985, '10': 13, '20': 1, '4000': 1}",1000,tcam
51,0.0,5.0,17.0,4.0,5.0,"{'0': 5980, '10': 19, '4000': 1}",1000,tcam
52,0.0,5.0,18.0,4.0,5.0,"{'0': 5984, '10': 15, '4000': 1}",1000,tcam